const {test}=require('node:test'),assert=require('node:assert/strict');
const S=require('../holiday-sync.js');
const year=(y,extra=[])=>Object.fromEntries(['01-01','03-01','05-05','06-06','08-15','10-03','10-09','12-25','02-01','02-02',...extra].map(d=>[`${y}-${d}`,['공휴일']]));
function setup(fetcher){const saved={};let applied,stamp=100000000;const storage={get:async()=>structuredClone(saved),set:async v=>Object.assign(saved,structuredClone(v))};const calendar={useDownloaded:v=>applied=v};return {saved,storage,calendar,get applied(){return applied;},advance:()=>stamp+=86400001,sync:S.create(storage,calendar,fetcher,()=>stamp)};}
test('valid new year is downloaded without credentials and applied once per day',async()=>{let calls=0;const h=setup(async(url,options)=>{calls++;assert.equal(url,S.URL);assert.equal(options.credentials,'omit');assert.equal(options.referrerPolicy,'no-referrer');assert.equal(options.body,undefined);return new Response(JSON.stringify({'2028':year(2028,['09-13'])}));});await h.sync.refresh();assert.ok(h.applied['2028'].includes('09-13'));await h.sync.refresh();assert.equal(calls,1);h.advance();await h.sync.refresh();assert.equal(calls,2);});
test('failure keeps last successful cache and uses it after worker restart',async()=>{let fail=false;const h=setup(async()=>{if(fail)throw Error('offline');return new Response(JSON.stringify({'2028':year(2028)}));});await h.sync.refresh();fail=true;h.advance();await h.sync.refresh();assert.ok(h.saved.holidayCache.error);assert.ok(h.applied['2028']);const restarted=S.create(h.storage,h.calendar,async()=>{throw Error('offline');},()=>200000000);await restarted.refresh();assert.ok(h.applied['2028']);});
test('malformed, partial and invalid dates are rejected',()=>{for(const bad of [{},[],{'2028':{}},{'2028':{...year(2028),'2028-02-30':['bad']}},{'2028':{...year(2028),'2028-03-02':'bad'}}])assert.throws(()=>S.validate(bad));});
test('downloaded replacement honors removed dates while retaining absent cached years',async()=>{let step=0;const h=setup(async()=>new Response(JSON.stringify(step++?{'2028':year(2028)}:{'2028':year(2028,['09-13']),'2029':year(2029)})));await h.sync.refresh();h.advance();await h.sync.refresh();assert.ok(!h.applied['2028'].includes('09-13'));assert.ok(h.applied['2029']);});
test('oversized download does not overwrite calendar',async()=>{const h=setup(async()=>new Response(' '.repeat(524289)));await h.sync.refresh();assert.match(h.saved.holidayCache.error,/크기/);assert.equal(h.applied,undefined);});

test('remote year affects workday calculation and absent year still uses weekends',()=>{const K=require('../calendar.js');try{K.useDownloaded(S.validate({'2028':year(2028,['09-13'])}));assert.equal(K.subtractWorkdays('2028-09-14',1),'2028-09-12');assert.equal(K.subtractWorkdays('2029-09-18',1),'2029-09-17');}finally{K.useDownloaded({});}});
